package domain;

// Generated 13-feb-2014 18:05:56 by Hibernate Tools 4.0.0

/**
 * CallesUll generated by hbm2java
 */
public class CallesUll implements java.io.Serializable {

	private CallesUllId id;

	public CallesUll() {
	}

	public CallesUll(CallesUllId id) {
		this.id = id;
	}

	public CallesUllId getId() {
		return this.id;
	}

	public void setId(CallesUllId id) {
		this.id = id;
	}

}
