package domain;

// Generated 13-feb-2014 18:05:56 by Hibernate Tools 4.0.0

/**
 * DomiciliosUll generated by hbm2java
 */
public class DomiciliosUll implements java.io.Serializable {

	private DomiciliosUllId id;

	public DomiciliosUll() {
	}

	public DomiciliosUll(DomiciliosUllId id) {
		this.id = id;
	}

	public DomiciliosUllId getId() {
		return this.id;
	}

	public void setId(DomiciliosUllId id) {
		this.id = id;
	}

}
