package domain;

// Generated 13-feb-2014 18:05:56 by Hibernate Tools 4.0.0

/**
 * EstudiosUll generated by hbm2java
 */
public class EstudiosUll implements java.io.Serializable {

	private EstudiosUllId id;

	public EstudiosUll() {
	}

	public EstudiosUll(EstudiosUllId id) {
		this.id = id;
	}

	public EstudiosUllId getId() {
		return this.id;
	}

	public void setId(EstudiosUllId id) {
		this.id = id;
	}

}
