package domain;

// Generated 13-feb-2014 18:05:56 by Hibernate Tools 4.0.0

/**
 * EstudiosUllId generated by hbm2java
 */
public class EstudiosUllId implements java.io.Serializable {

	private String codmun;
	private String codigoEst;
	private String nivelEst;
	private String codigoIne;
	private String codigoIstac;
	private String descripcion;

	public EstudiosUllId() {
	}

	public EstudiosUllId(String codmun, String codigoEst, String nivelEst,
			String codigoIne, String codigoIstac, String descripcion) {
		this.codmun = codmun;
		this.codigoEst = codigoEst;
		this.nivelEst = nivelEst;
		this.codigoIne = codigoIne;
		this.codigoIstac = codigoIstac;
		this.descripcion = descripcion;
	}

	public String getCodmun() {
		return this.codmun;
	}

	public void setCodmun(String codmun) {
		this.codmun = codmun;
	}

	public String getCodigoEst() {
		return this.codigoEst;
	}

	public void setCodigoEst(String codigoEst) {
		this.codigoEst = codigoEst;
	}

	public String getNivelEst() {
		return this.nivelEst;
	}

	public void setNivelEst(String nivelEst) {
		this.nivelEst = nivelEst;
	}

	public String getCodigoIne() {
		return this.codigoIne;
	}

	public void setCodigoIne(String codigoIne) {
		this.codigoIne = codigoIne;
	}

	public String getCodigoIstac() {
		return this.codigoIstac;
	}

	public void setCodigoIstac(String codigoIstac) {
		this.codigoIstac = codigoIstac;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstudiosUllId))
			return false;
		EstudiosUllId castOther = (EstudiosUllId) other;

		return ((this.getCodmun() == castOther.getCodmun()) || (this
				.getCodmun() != null && castOther.getCodmun() != null && this
				.getCodmun().equals(castOther.getCodmun())))
				&& ((this.getCodigoEst() == castOther.getCodigoEst()) || (this
						.getCodigoEst() != null
						&& castOther.getCodigoEst() != null && this
						.getCodigoEst().equals(castOther.getCodigoEst())))
				&& ((this.getNivelEst() == castOther.getNivelEst()) || (this
						.getNivelEst() != null
						&& castOther.getNivelEst() != null && this
						.getNivelEst().equals(castOther.getNivelEst())))
				&& ((this.getCodigoIne() == castOther.getCodigoIne()) || (this
						.getCodigoIne() != null
						&& castOther.getCodigoIne() != null && this
						.getCodigoIne().equals(castOther.getCodigoIne())))
				&& ((this.getCodigoIstac() == castOther.getCodigoIstac()) || (this
						.getCodigoIstac() != null
						&& castOther.getCodigoIstac() != null && this
						.getCodigoIstac().equals(castOther.getCodigoIstac())))
				&& ((this.getDescripcion() == castOther.getDescripcion()) || (this
						.getDescripcion() != null
						&& castOther.getDescripcion() != null && this
						.getDescripcion().equals(castOther.getDescripcion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodmun() == null ? 0 : this.getCodmun().hashCode());
		result = 37 * result
				+ (getCodigoEst() == null ? 0 : this.getCodigoEst().hashCode());
		result = 37 * result
				+ (getNivelEst() == null ? 0 : this.getNivelEst().hashCode());
		result = 37 * result
				+ (getCodigoIne() == null ? 0 : this.getCodigoIne().hashCode());
		result = 37
				* result
				+ (getCodigoIstac() == null ? 0 : this.getCodigoIstac()
						.hashCode());
		result = 37
				* result
				+ (getDescripcion() == null ? 0 : this.getDescripcion()
						.hashCode());
		return result;
	}

}
