package domain;

// Generated 13-feb-2014 18:05:56 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * HabitantesUllId generated by hbm2java
 */
public class HabitantesUllId implements java.io.Serializable {

	private String codmun;
	private String hojapad;
	private String sexo;
	private Date fechanacim;
	private String codigoEst;

	public HabitantesUllId() {
	}

	public HabitantesUllId(String codmun, String hojapad, String sexo,
			Date fechanacim, String codigoEst) {
		this.codmun = codmun;
		this.hojapad = hojapad;
		this.sexo = sexo;
		this.fechanacim = fechanacim;
		this.codigoEst = codigoEst;
	}

	public String getCodmun() {
		return this.codmun;
	}

	public void setCodmun(String codmun) {
		this.codmun = codmun;
	}

	public String getHojapad() {
		return this.hojapad;
	}

	public void setHojapad(String hojapad) {
		this.hojapad = hojapad;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Date getFechanacim() {
		return this.fechanacim;
	}

	public void setFechanacim(Date fechanacim) {
		this.fechanacim = fechanacim;
	}

	public String getCodigoEst() {
		return this.codigoEst;
	}

	public void setCodigoEst(String codigoEst) {
		this.codigoEst = codigoEst;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HabitantesUllId))
			return false;
		HabitantesUllId castOther = (HabitantesUllId) other;

		return ((this.getCodmun() == castOther.getCodmun()) || (this
				.getCodmun() != null && castOther.getCodmun() != null && this
				.getCodmun().equals(castOther.getCodmun())))
				&& ((this.getHojapad() == castOther.getHojapad()) || (this
						.getHojapad() != null && castOther.getHojapad() != null && this
						.getHojapad().equals(castOther.getHojapad())))
				&& ((this.getSexo() == castOther.getSexo()) || (this.getSexo() != null
						&& castOther.getSexo() != null && this.getSexo()
						.equals(castOther.getSexo())))
				&& ((this.getFechanacim() == castOther.getFechanacim()) || (this
						.getFechanacim() != null
						&& castOther.getFechanacim() != null && this
						.getFechanacim().equals(castOther.getFechanacim())))
				&& ((this.getCodigoEst() == castOther.getCodigoEst()) || (this
						.getCodigoEst() != null
						&& castOther.getCodigoEst() != null && this
						.getCodigoEst().equals(castOther.getCodigoEst())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodmun() == null ? 0 : this.getCodmun().hashCode());
		result = 37 * result
				+ (getHojapad() == null ? 0 : this.getHojapad().hashCode());
		result = 37 * result
				+ (getSexo() == null ? 0 : this.getSexo().hashCode());
		result = 37
				* result
				+ (getFechanacim() == null ? 0 : this.getFechanacim()
						.hashCode());
		result = 37 * result
				+ (getCodigoEst() == null ? 0 : this.getCodigoEst().hashCode());
		return result;
	}

}
