package domain;

// Generated 13-feb-2014 18:05:56 by Hibernate Tools 4.0.0

/**
 * HabitantesUll generated by hbm2java
 */
public class HabitantesUll implements java.io.Serializable {

	private HabitantesUllId id;

	public HabitantesUll() {
	}

	public HabitantesUll(HabitantesUllId id) {
		this.id = id;
	}

	public HabitantesUllId getId() {
		return this.id;
	}

	public void setId(HabitantesUllId id) {
		this.id = id;
	}

}
