package domain;

// Generated 13-feb-2014 18:05:56 by Hibernate Tools 4.0.0

/**
 * TViasUll generated by hbm2java
 */
public class TViasUll implements java.io.Serializable {

	private TViasUllId id;

	public TViasUll() {
	}

	public TViasUll(TViasUllId id) {
		this.id = id;
	}

	public TViasUllId getId() {
		return this.id;
	}

	public void setId(TViasUllId id) {
		this.id = id;
	}

}
