package domain;

// Generated 13-feb-2014 18:05:56 by Hibernate Tools 4.0.0

/**
 * TViasUllId generated by hbm2java
 */
public class TViasUllId implements java.io.Serializable {

	private String tvian;
	private String nombre;

	public TViasUllId() {
	}

	public TViasUllId(String tvian, String nombre) {
		this.tvian = tvian;
		this.nombre = nombre;
	}

	public String getTvian() {
		return this.tvian;
	}

	public void setTvian(String tvian) {
		this.tvian = tvian;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TViasUllId))
			return false;
		TViasUllId castOther = (TViasUllId) other;

		return ((this.getTvian() == castOther.getTvian()) || (this.getTvian() != null
				&& castOther.getTvian() != null && this.getTvian().equals(
				castOther.getTvian())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTvian() == null ? 0 : this.getTvian().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
