package domain;

// Generated 13-feb-2014 18:05:56 by Hibernate Tools 4.0.0

/**
 * ViviendasUllId generated by hbm2java
 */
public class ViviendasUllId implements java.io.Serializable {

	private String codmun;
	private String idvianum;
	private String hojapad;
	private String codviamuni;

	public ViviendasUllId() {
	}

	public ViviendasUllId(String codmun, String idvianum, String hojapad,
			String codviamuni) {
		this.codmun = codmun;
		this.idvianum = idvianum;
		this.hojapad = hojapad;
		this.codviamuni = codviamuni;
	}

	public String getCodmun() {
		return this.codmun;
	}

	public void setCodmun(String codmun) {
		this.codmun = codmun;
	}

	public String getIdvianum() {
		return this.idvianum;
	}

	public void setIdvianum(String idvianum) {
		this.idvianum = idvianum;
	}

	public String getHojapad() {
		return this.hojapad;
	}

	public void setHojapad(String hojapad) {
		this.hojapad = hojapad;
	}

	public String getCodviamuni() {
		return this.codviamuni;
	}

	public void setCodviamuni(String codviamuni) {
		this.codviamuni = codviamuni;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViviendasUllId))
			return false;
		ViviendasUllId castOther = (ViviendasUllId) other;

		return ((this.getCodmun() == castOther.getCodmun()) || (this
				.getCodmun() != null && castOther.getCodmun() != null && this
				.getCodmun().equals(castOther.getCodmun())))
				&& ((this.getIdvianum() == castOther.getIdvianum()) || (this
						.getIdvianum() != null
						&& castOther.getIdvianum() != null && this
						.getIdvianum().equals(castOther.getIdvianum())))
				&& ((this.getHojapad() == castOther.getHojapad()) || (this
						.getHojapad() != null && castOther.getHojapad() != null && this
						.getHojapad().equals(castOther.getHojapad())))
				&& ((this.getCodviamuni() == castOther.getCodviamuni()) || (this
						.getCodviamuni() != null
						&& castOther.getCodviamuni() != null && this
						.getCodviamuni().equals(castOther.getCodviamuni())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodmun() == null ? 0 : this.getCodmun().hashCode());
		result = 37 * result
				+ (getIdvianum() == null ? 0 : this.getIdvianum().hashCode());
		result = 37 * result
				+ (getHojapad() == null ? 0 : this.getHojapad().hashCode());
		result = 37
				* result
				+ (getCodviamuni() == null ? 0 : this.getCodviamuni()
						.hashCode());
		return result;
	}

}
