package domain;

// Generated 13-feb-2014 18:05:56 by Hibernate Tools 4.0.0

/**
 * ViviendasUll generated by hbm2java
 */
public class ViviendasUll implements java.io.Serializable {

	private ViviendasUllId id;

	public ViviendasUll() {
	}

	public ViviendasUll(ViviendasUllId id) {
		this.id = id;
	}

	public ViviendasUllId getId() {
		return this.id;
	}

	public void setId(ViviendasUllId id) {
		this.id = id;
	}

}
